/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.96
 * Generated at: 2021-02-21 11:32:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.manage;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class admin_005findex_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/manage/admin_menu.jsp", Long.valueOf(1613906799527L));
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\"/>\r\n");
      out.write("    <title>简单通用文章系统后台管理模板</title>\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"css/common.css\"/>\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"css/main.css\"/>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"topbar-wrap white\">\r\n");
      out.write("    <div class=\"topbar-inner clearfix\">\r\n");
      out.write("        <div class=\"topbar-logo-wrap clearfix\">\r\n");
      out.write("            <h1 class=\"topbar-logo none\"><a href=\"index.html\" class=\"navbar-brand\">后台管理</a></h1>\r\n");
      out.write("            <ul class=\"navbar-list clearfix\">\r\n");
      out.write("                <li><a class=\"on\" href=\"index.html\">首页</a></li>\r\n");
      out.write("                <li><a href=\"#\" target=\"_blank\">网站首页</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"top-info-wrap\">\r\n");
      out.write("            <ul class=\"top-info-list clearfix\">\r\n");
      out.write("                <li><a href=\"#\">管理员</a></li>\r\n");
      out.write("                <li><a href=\"#\">修改密码</a></li>\r\n");
      out.write("                <li><a href=\"#\">退出</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"container clearfix\">\r\n");
      out.write("    <div class=\"sidebar-wrap\">\r\n");
      out.write("        <div class=\"sidebar-title\">\r\n");
      out.write("            <h1>菜单</h1>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"sidebar-content\">\r\n");
      out.write("            <ul class=\"sidebar-list\">\r\n");
      out.write("                <li>\r\n");
      out.write("                    <a href=\"#\"><i class=\"icon-font\">&#xe003;</i>常用操作</a>\r\n");
      out.write("                    <ul class=\"sub-menu\">\r\n");
      out.write("                        <li><a href=\"design.html\"><i class=\"icon-font\">&#xe008;</i>作品管理</a></li>\r\n");
      out.write("                        <li><a href=\"design.html\"><i class=\"icon-font\">&#xe005;</i>博文管理</a></li>\r\n");
      out.write("                        <li><a href=\"design.html\"><i class=\"icon-font\">&#xe006;</i>分类管理</a></li>\r\n");
      out.write("                        <li><a href=\"design.html\"><i class=\"icon-font\">&#xe004;</i>留言管理</a></li>\r\n");
      out.write("                        <li><a href=\"design.html\"><i class=\"icon-font\">&#xe012;</i>评论管理</a></li>\r\n");
      out.write("                        <li><a href=\"design.html\"><i class=\"icon-font\">&#xe052;</i>友情链接</a></li>\r\n");
      out.write("                        <li><a href=\"design.html\"><i class=\"icon-font\">&#xe033;</i>广告管理</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <a href=\"#\"><i class=\"icon-font\">&#xe018;</i>系统管理</a>\r\n");
      out.write("                    <ul class=\"sub-menu\">\r\n");
      out.write("                        <li><a href=\"system.html\"><i class=\"icon-font\">&#xe017;</i>系统设置</a></li>\r\n");
      out.write("                        <li><a href=\"system.html\"><i class=\"icon-font\">&#xe037;</i>清理缓存</a></li>\r\n");
      out.write("                        <li><a href=\"system.html\"><i class=\"icon-font\">&#xe046;</i>数据备份</a></li>\r\n");
      out.write("                        <li><a href=\"system.html\"><i class=\"icon-font\">&#xe045;</i>数据还原</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>");
      out.write("\r\n");
      out.write("    <!--/sidebar-->\r\n");
      out.write("    <div class=\"main-wrap\">\r\n");
      out.write("        <div class=\"crumb-wrap\">\r\n");
      out.write("            <div class=\"crumb-list\"><i class=\"icon-font\">&#xe06b;</i><span>欢迎使用『学习猿地』博客程序，建博的首选工具。</span></div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"result-wrap\">\r\n");
      out.write("            <div class=\"result-title\">\r\n");
      out.write("                <h1>快捷操作</h1>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"result-content\">\r\n");
      out.write("                <div class=\"short-wrap\">\r\n");
      out.write("                    <a href=\"insert.html\"><i class=\"icon-font\">&#xe001;</i>新增作品</a>\r\n");
      out.write("                    <a href=\"insert.html\"><i class=\"icon-font\">&#xe005;</i>新增博文</a>\r\n");
      out.write("                    <a href=\"insert.html\"><i class=\"icon-font\">&#xe048;</i>新增作品分类</a>\r\n");
      out.write("                    <a href=\"insert.html\"><i class=\"icon-font\">&#xe041;</i>新增博客分类</a>\r\n");
      out.write("                    <a href=\"#\"><i class=\"icon-font\">&#xe01e;</i>作品评论</a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"result-wrap\">\r\n");
      out.write("            <div class=\"result-title\">\r\n");
      out.write("                <h1>系统基本信息</h1>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"result-content\">\r\n");
      out.write("                <ul class=\"sys-info-list\">\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <label class=\"res-lab\">操作系统</label><span class=\"res-info\">WINNT</span>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <label class=\"res-lab\">运行环境</label><span class=\"res-info\">Apache/2.2.21 (Win64) PHP/7.3.10</span>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <label class=\"res-lab\">PHP运行方式</label><span class=\"res-info\">apache2handler</span>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <label class=\"res-lab\">静静设计-版本</label><span class=\"res-info\">v-0.1</span>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <label class=\"res-lab\">上传附件限制</label><span class=\"res-info\">2M</span>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <label class=\"res-lab\">北京时间</label><span class=\"res-info\">2019年3月18日 21:08:24</span>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <label class=\"res-lab\">服务器域名/IP</label><span class=\"res-info\">localhost [ 127.0.0.1 ]</span>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <label class=\"res-lab\">Host</label><span class=\"res-info\">127.0.0.1</span>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"result-wrap\">\r\n");
      out.write("            <div class=\"result-title\">\r\n");
      out.write("                <h1>使用帮助</h1>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"result-content\">\r\n");
      out.write("                <ul class=\"sys-info-list\">\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <label class=\"res-lab\">更多模板：</label><span class=\"res-info\"><a href=\"http://www.lmonkey.com/\" target=\"_blank\">学习猿地</a></span>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!--/main-->\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
